joint_limits:
  right_j0:
    has_velocity_limits: true
    max_velocity: 1.6
    has_acceleration_limits: true
    max_acceleration: 8.0
  right_j1:
    has_velocity_limits: true
    max_velocity: 1.3
    has_acceleration_limits: true
    max_acceleration: 8.0
  right_j2:
    has_velocity_limits: true
    max_velocity: 1.9
    has_acceleration_limits: true
    max_acceleration: 8.0
  right_j3:
    has_velocity_limits: true
    max_velocity: 1.9
    has_acceleration_limits: true
    max_acceleration: 8.0
  right_j4:
    has_velocity_limits: true
    max_velocity: 3.4
    has_acceleration_limits: true
    max_acceleration: 10.0
  right_j5:
    has_velocity_limits: true
    max_velocity: 3.4
    has_acceleration_limits: true
    max_acceleration: 10.0
  right_j6:
    has_velocity_limits: true
    max_velocity: 4.5
    has_acceleration_limits: true
    max_acceleration: 10.0
